### ISSUE TITLE
Add missing package

### ISSUE THREAD

**Issue by owolo** [bntr00t/crowntool#4]
For socks5 checking, you gotta add in requirements.txt **httpx-socks**, since its missing it. Also, I suppose that proxy checking isn't working.

**Comment by bntr00t** [comment]
Thanks, about the proxy checking what issue are you getting

**Comment by bntr00t** [comment]
![image](https://user-images.githubusercontent.com/58895443/183123199-0d0a30d1-fd58-4441-89a4-8cf113ac80e6.png)
should all be working
